export enum PERMISSIONS_ENUM {
  CREATE_ACCOUNT = "CREATE_ACCOUNT",
  READ_ACCOUNT = "READ_ACCOUNT",
  UPDATE_ACCOUNT = "UPDATE_ACCOUNT",
  DELETE_ACCOUNT = "DELETE_ACCOUNT",

  CREATE_PRODUCT = "CREATE_PRODUCT",
  READ_PRODUCT = "READ_PRODUCT",
  UPDATE_PRODUCT = "UPDATE_PRODUCT",
  DELETE_PRODUCT = "DELETE_PRODUCT",

  CREATE_CART = "CREATE_CART",
  READ_CART = "READ_CART",
  UPDATE_CART = "UPDATE_CART",
  DELETE_CART = "DELETE_CART",

  CREATE_ORDER = "CREATE_ORDER",
  READ_ORDER = "READ_ORDER",
  UPDATE_ORDER = "UPDATE_ORDER",
  DELETE_ORDER = "DELETE_ORDER",

  CREATE_INVOICE = "CREATE_INVOICE",
  READ_INVOICE = "READ_INVOICE",
  UPDATE_INVOICE = "UPDATE_INVOICE",
  DELETE_INVOICE = "DELETE_INVOICE",

  CREATE_FEEDBACK = "CREATE_FEEDBACK",
  READ_FEEDBACK = "READ_FEEDBACK",
  UPDATE_FEEDBACK = "UPDATE_FEEDBACK",
  DELETE_FEEDBACK = "DELETE_FEEDBACK",

  CREATE_SHIPPING = "CREATE_SHIPPING",
  READ_SHIPPING = "READ_SHIPPING",
  UPDATE_SHIPPING = "UPDATE_SHIPPING",
  DELETE_SHIPPING = "DELETE_SHIPPING",

  CREATE_SHOP = "CREATE_SHOP",
  READ_SHOP = "READ_SHOP",
  UPDATE_SHOP = "UPDATE_SHOP",
  DELETE_SHOP = "DELETE_SHOP",

  CREATE_CLASSIFY = "CREATE_CLASSIFY",
  READ_CLASSIFY = "READ_CLASSIFY",
  UPDATE_CLASSIFY = "UPDATE_CLASSIFY",
  DELETE_CLASSIFY = "DELETE_CLASSIFY",

  CREATE_SEARCH_HISTORY = "CREATE_SEARCH_HISTORY",
  READ_SEARCH_HISTORY = "READ_SEARCH_HISTORY",
  UPDATE_SEARCH_HISTORY = "UPDATE_SEARCH_HISTORY",
  DELETE_SEARCH_HISTORY = "DELETE_SEARCH_HISTORY",

  GRANT_PERMISSION = "GRANT_PERMISSION",
  READ_ANALYSIS = "READ_ANALYSIS",
}
